### ISSUE TITLE
Personalize Zsh Configuration

### ISSUE THREAD

**Issue by ZeroKnight** [ZeroKnight/dotfiles#5]
Ditch the slow frameworks loaded with extras that I don't need and/or conflict with my own stuff. Create a "framework" of my own tailor-made to my existing configuration (while lovingly yanking bits and pieces that I like from the frameworks I'm ditching).
### Todo
- [x] Load run-help properly
  - Alias to ~~'help'~~  'zhelp'
- [x] Set up Completions and zstyles
- [x] Set up input/zle
- [x] Finish importing any last decent bits of frameworks
- [x] Git Git Git
- [x] #6 
- [x] Set up Prompt (low load order! ~~will depend on functions from other modules like `git`~~)
- [x] Purge all remnants of frameworks
